/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import control.ControlRegistro;
import java.awt.Component;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import modelo.Estudiante;

/**
 *
 * @author Juan David Osorio y Nicolás Estupiñán
 */
public class Ventana extends javax.swing.JFrame {

    private ControlRegistro controlRegistro;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        controlRegistro = new ControlRegistro();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeleccionarArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacion = new javax.swing.JTextArea();
        Titulo = new javax.swing.JLabel();
        btnMostrarInformacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSeleccionarArchivo.setText("Seleccionar archivo");
        btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtInformacion.setEditable(false);
        txtInformacion.setColumns(20);
        txtInformacion.setRows(5);
        jScrollPane1.setViewportView(txtInformacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 320, 140));

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setText("Informacion Estudiantes");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 220, 30));

        btnMostrarInformacion.setText("Mostrar Información");
        btnMostrarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInformacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
       
        String rutaArchivo=guardarRutaArchivoSeleccionado();
        
        cargaDatos(rutaArchivo);
        
    }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

    
    /**
     * Método que carga el archivo y llama a los métodos correspondientes para
     * la obtención de la lista con las inscripciones, para posteriormente registrar
     * los estudiantes.
     * @param rutaArchivo 
     */
    private void cargaDatos(String rutaArchivo) {
        File archivoAConvertir=new File(rutaArchivo);
        ArrayList<String> datos = new ArrayList<>();
        datos = controlRegistro.cargarLista(archivoAConvertir);
        controlRegistro.registrarEstudiante(datos);
    }

    /**
     * Método que muestra una ventana emergente al usuario para que escoja el 
     * archivo de texto con las inscripciones que se leerá.
 
     * @return la ruta del archivo que se escogió.
     */
    public String guardarRutaArchivoSeleccionado() {
        JFileChooser chooser = new JFileChooser();
        String rutaArchivo=null;
        
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        Component parent = null;
        int returnVal = chooser.showSaveDialog(parent);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            
            String nombreCarpeta = chooser.getSelectedFile().getParent();
            String nombreArchivo = chooser.getSelectedFile().getName();
            rutaArchivo = nombreCarpeta + "\\" + nombreArchivo;
        }
        
        return rutaArchivo;
    }

    private void btnMostrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInformacionActionPerformed
        mostrarInformacion();
    }//GEN-LAST:event_btnMostrarInformacionActionPerformed

    /**
     * Método que muestra en la interfaz gráfica los nombres de los estudiantes
     * con su número de materias inscritas.
     */
    private void mostrarInformacion() {
        String informacion = "";
        for (Estudiante estudiante : controlRegistro.listarEstudiantes()) {
            informacion+= "\n"+ estudiante.getNombre() + " "
                    + controlRegistro.totalMateriasEstudiante(estudiante)
                    + " materias";
        }
        txtInformacion.setText(informacion);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnMostrarInformacion;
    private javax.swing.JButton btnSeleccionarArchivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtInformacion;
    // End of variables declaration//GEN-END:variables
}
